name: CI React Docker

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Build da aplicação React
  build-react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalar Dependências
        run: npm install

      - name: Build do Projeto
        run: npm run build

  # Job 2: Construção e Push da Imagem Docker
  docker-build:
    runs-on: ubuntu-latest
    needs: build-react # Garante que o build do React passe antes de começar
    steps:
      - uses: actions/checkout@v4

      - name: Login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # Use Secrets para segurança
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build da Imagem Docker
        run: docker build -t aulagha .

      - name: Tag e Push da Imagem
        run: |
          docker tag aulagha ${{ secrets.DOCKER_USERNAME }}/aulagha:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/aulagha:latest